version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./nginx-fpm/
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    volumes:
      - ./App/:/var/www/html/:rw
networks:
  nginx_network: